services:
  - type: web
    name: feedback-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free

  - type: web
    name: feedback-frontend
    env: node
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
